server:
  port: 8070     
spring:
  application:
    name: farmer-es-service    
  data:
    elasticsearch:
      cluster-name: ${cluster.name}
      cluster-nodes: ${cluster.nodes}
      local: false
      repositories:
        enabled: true               
eureka:
  instance:
    hostname: eureka         # 指定该Eureka实例的主机名
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://user:user@${eureka.instance.hostname}:8761/eureka/