server:
  port: 8070                    
eureka:
  instance:
    hostname: eureka         # 指定该Eureka实例的主机名
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://user:user@localhost:8761/eureka/