server:
  port: 8070                    
spring:
  data:
    elasticsearch:
      cluster-name: qf
      cluster-nodes: 172.31.7.1:9300
      local: false
      repositories:
        enabled: true
eureka:
  instance:
    hostname: eureka         # 指定该Eureka实例的主机名
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://user:user@${eureka.instance.hostname}:8761/eureka/