server:
  port: 8761                    # 指定该Eureka实例的端口

eureka:
  instance:
    hostname: eureka         # 指定该Eureka实例的主机名
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://user:user@${eureka.instance.hostname}:${server.port}/eureka/
security:
  basic:
    enabled: true
  user:
    name: user
    password: user