server:
  port: 9999
  contextPath: /auth

eureka:
  instance:
    hostname: eureka         # 指定该Eureka实例的主机名
    preferIpAddress: true
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://user:user@${eureka.instance.hostname}:8761/eureka/

ribbon:
  eureka:
    enabled: true

security:
  user:
    password: qinfei
  oauth2:
    client:
      client-id: farmer
      client-secret: qf
      scope: read,write
      auto-approve-scopes: '.*'
spring:
  datasource:  
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    platform: ${spring.datasource.platform}
    driver-class-name: ${spring.datasource.driver}
  

logging:
  level:
    org.springframework.security: DEBUG