server:
  port: 8000
spring:
  application:
    name: farmer-user-service    # 项目名称尽量用小写
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                           # 指定数据源
    url: ${jpa.datasource.url}
    username: ${jpa.datasource.username}
    password: ${jpa.datasource.password}
    platform: ${jpa.datasource.platform}                        # 指定数据源类型
    schema: classpath:schema.sql        # 指定h2数据库的建表脚本
    data: classpath:data.sql            # 指定h2数据库的insert脚本
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:user@${eureka.instance.hostname}:8761/eureka/    # 指定注册中心的地址
  instance:
    hostname: eureka         # 指定该Eureka实例的主机名
    preferIpAddress: true