server:
  port: 8010
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                           # 指定数据源
    url: ${jpa.datasource.url}
    username: ${jpa.datasource.username}
    password: ${jpa.datasource.password}
    platform: ${jpa.datasource.platform}                        # 指定数据源类型
    schema: classpath:schema.sql        # 指定h2数据库的建表脚本
  kafka:
    bootstrap-servers: 172.31.8.1:9092,172.31.8.2:9092,172.31.8.3:9093
    consumer: 
      group-id: farmer
    template:
      default-topic: farmer-store
    listener:
      concurrency: 3
    producer: 
      batch-size: 1000
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:user@${eureka.instance.hostname}:8761/eureka/    # 指定注册中心的地址
  instance:
    hostname: eureka         # 指定该Eureka实例的主机名
    preferIpAddress: true