server:
  port: 8090
spring:
  application:
    name: farmer-workflow-service
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:                           # 指定数据源
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    platform: ${spring.datasource.platform}
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:user@${eureka.instance.hostname}:8761/eureka/    # 指定注册中心的地址
  instance:
    hostname: eureka         # 指定该Eureka实例的主机名
    preferIpAddress: true