server:
  port: 8090
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    datasource: ${db.datasource}
    hibernate:
      ddl-auto: update
  datasource:                           # 指定数据源
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: ${db.driver}
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:user@${eureka.instance.hostname}:8761/eureka/    # 指定注册中心的地址
  instance:
    hostname: eureka         # 指定该Eureka实例的主机名
    preferIpAddress: true