server:
  port: 8080

eureka:
  instance:
    hostname: eureka         # 指定该Eureka实例的主机名
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://user:user@${eureka.instance.hostname}:8761/eureka/

ribbon:
  eureka:
    enabled: true

security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'

facebook:
  client:
    clientId: 930719640364588
    clientSecret: f504b5c94844715f7f498f2a1117d23e
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me
github:
  client:
    clientId: 3a6a4800187901f0bfc1
    clientSecret: 34b24ec6a19a4afd2b7fbb4d698f5f4472c5ae71
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

logging:
  level:
    org.springframework.security: DEBUG
